apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 77bb6026-713e-4963-b675-a427fb5fbd27
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: create-user-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/create_user
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /onboarding/create_user
